# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-17 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5206\u7c7b\u540d')),
                ('is_show', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u8bdd\u9898\u5206\u7c7b',
                'verbose_name_plural': '\u8bdd\u9898\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u8bdd\u9898\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u8bdd\u9898\u6b63\u6587')),
                ('is_top', models.BooleanField(default=False, verbose_name='\u8bdd\u9898\u662f\u5426\u7f6e\u9876')),
                ('is_show', models.BooleanField(default=True, verbose_name='\u8bdd\u9898\u662f\u5426\u663e\u793a')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6700\u540e\u4e00\u6b21\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bdd\u9898',
                'verbose_name_plural': '\u8bdd\u9898',
            },
        ),
    ]
