# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-17 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bdd\u9898\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Category', verbose_name='\u8bdd\u9898\u5206\u7c7b'),
        ),
    ]
