# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-16 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='\u8bdd\u9898\u662f\u5426\u663e\u793a'),
        ),
    ]
