# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='\u8bdd\u9898\u662f\u5426\u663e\u793a'),
        ),
    ]
