# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-16 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='add_time',
        ),
    ]
