# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-18 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170917_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='\u90ae\u7bb1')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('class_name', models.CharField(max_length=30, verbose_name='\u6240\u5728\u73ed\u7ea7')),
                ('qq', models.CharField(max_length=20, verbose_name='qq\u53f7\u7801')),
                ('phone', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('reason', models.TextField(verbose_name='\u7533\u8bf7\u7406\u7531')),
                ('status', models.CharField(choices=[('0', '\u672a\u5904\u7406'), ('1', '\u672a\u901a\u8fc7'), ('2', '\u5df2\u901a\u8fc7')], max_length=1, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('apply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u62db\u65b0\u62a5\u540d',
                'verbose_name_plural': '\u7528\u6237\u62db\u65b0\u62a5\u540d',
            },
        ),
    ]
